### ISSUE TITLE
Procedure of adding a datasets

### ISSUE THREAD

**Issue by pmcwhannel** [DeltaE/delta-e-utils#11]
The procedure of adding datasets should indicate all the actions a member should consider and undertake when adding a dataset. These actions should include (not exclusively): 1) Following the procedure on providence/governance of data, 2) Following the procedure on data documentation see #10 , and 3) Following the procedure on adding scripts see #8. Ultimately, this master procedure provides members with an end-2-end process on how to contribute to adding datasets to delta-e-utils.

A successful PR for this will include:
- [x] A user flow diagram presented to the data team. (See [blog](https://careerfoundry.com/en/blog/ux-design/what-are-user-flows/))
- [x] Presentation to group (DeltaE) the proposed flow diagram. 
- [x] A procedure added to the ReadTheDocs.

**Comment by malshebo** [comment]
User flow diagram is nearly complete. It requires questions regarding centralization of data and where it will be stored.
User flow diagram requires a conversation regarding governance/providence procedures, so that they can be added in to the diagram.
Presentation on February 16th
Document procedure will be written for read the doc after UI is completed

**Comment by pmcwhannel** [comment]
This was finished at the end of Mohammad's work term.
